name: Build and publish new package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean the solution
        run: dotnet clean

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: PackageRelease
          path: bin/Release/net9.0-windows/win-x64/
          overwrite: true

      - name: Create zip file
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ github.workspace }}\bin\Release\net9.0-windows\win-x64\* -DestinationPath .\release.1.0.${{ github.RUN_NUMBER  }}.zip
          
      - name: Create a new release and attach zip
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: "1.0.${{ github.RUN_NUMBER  }}"
          prerelease: false
          make_latest: true
          files: |
            release.1.0.${{ github.RUN_NUMBER  }}.zip
